import type { DashboardReview } from "@/lib/types"

function hoursAgo(hours: number): string {
  return new Date(Date.now() - hours * 60 * 60 * 1000).toISOString()
}

export const demoReviews: DashboardReview[] = [
  {
    id: "demo-1",
    reviewerName: "María González",
    reviewerPhotoUrl: "https://i.pravatar.cc/150?u=maria-gonzalez",
    rating: 5,
    reviewText: "Excelente atención, muy rápidos y el trato fue increíble. Volvería sin dudarlo.",
    generatedText: null,
    publishedText:
      "¡Muchas gracias María! Nos alegra mucho que hayas tenido una gran experiencia. Te esperamos pronto de nuevo 😊",
    status: "PUBLISHED",
    createdAt: hoursAgo(0.3),
  },
  {
    id: "demo-2",
    reviewerName: "Carlos López",
    reviewerPhotoUrl: null,
    rating: 1,
    reviewText: "Tardaron muchísimo en atenderme y cuando llegó el pedido estaba frío. Muy mala experiencia.",
    generatedText:
      "Hola Carlos, lamentamos mucho esta experiencia. No es el estándar que buscamos ofrecer. Nos gustaría contactarte para resolverlo, ¿podés escribirnos por privado?",
    publishedText: null,
    status: "GENERATED",
    createdAt: hoursAgo(0.9),
  },
  {
    id: "demo-3",
    reviewerName: "Ana Rodríguez",
    reviewerPhotoUrl: "https://i.pravatar.cc/150?u=ana-rodriguez",
    rating: 4,
    reviewText: "Muy buena experiencia en general, aunque el lugar estaba un poco lleno para la hora que fui.",
    generatedText: null,
    publishedText: "¡Gracias Ana! Tomamos nota para mejorar la organización en horas pico. Te esperamos pronto.",
    status: "PUBLISHED",
    createdAt: hoursAgo(3),
  },
  {
    id: "demo-4",
    reviewerName: "Juan Pérez",
    reviewerPhotoUrl: null,
    rating: 3,
    reviewText: "Está bien, nada extraordinario. El servicio cumple pero esperaba un poco más por el precio.",
    generatedText: "Gracias por tu comentario Juan, lo tenemos en cuenta para seguir mejorando la propuesta.",
    publishedText: null,
    status: "EDITED",
    createdAt: hoursAgo(6),
  },
  {
    id: "demo-5",
    reviewerName: "Lucía Fernández",
    reviewerPhotoUrl: "https://i.pravatar.cc/150?u=lucia-fernandez",
    rating: 5,
    reviewText: "¡Espectacular! El mejor servicio que probé en la zona, sin dudas voy a volver.",
    generatedText: null,
    publishedText: "¡Qué alegría leerte Lucía! Gracias por elegirnos, nos vemos pronto 🎉",
    status: "PUBLISHED",
    createdAt: hoursAgo(10),
  },
  {
    id: "demo-6",
    reviewerName: "Diego Martínez",
    reviewerPhotoUrl: null,
    rating: 1,
    reviewText: "Pésima atención del personal, me trataron muy mal cuando pregunté por un reclamo.",
    generatedText: null,
    publishedText: null,
    status: "GENERATED",
    createdAt: hoursAgo(18),
  },
  {
    id: "demo-7",
    reviewerName: "Sofía Ramírez",
    reviewerPhotoUrl: "https://i.pravatar.cc/150?u=sofia-ramirez",
    rating: 4,
    reviewText: "Buena relación calidad-precio, el lugar es cómodo y el personal amable.",
    generatedText: null,
    publishedText: "¡Gracias Sofía! Nos encanta que te hayas sentido cómoda. Esperamos verte de nuevo pronto.",
    status: "APPROVED",
    createdAt: hoursAgo(30),
  },
  {
    id: "demo-8",
    reviewerName: "Martín Gómez",
    reviewerPhotoUrl: null,
    rating: 5,
    reviewText: "Todo perfecto, desde la reserva hasta la atención en el lugar. Muy recomendable.",
    generatedText: null,
    publishedText: "¡Gracias Martín! Nos alegra haber cumplido tus expectativas. ¡Hasta la próxima!",
    status: "PUBLISHED",
    createdAt: hoursAgo(48),
  },
  {
    id: "demo-9",
    reviewerName: "Camila López",
    reviewerPhotoUrl: "https://i.pravatar.cc/150?u=camila-lopez",
    rating: 2,
    reviewText: "La atención fue lenta y el pedido llegó incompleto, tuve que reclamar para que lo completaran.",
    generatedText:
      "Hola Camila, lamentamos el inconveniente con tu pedido. Vamos a revisar qué pasó para que no se repita.",
    publishedText: null,
    status: "GENERATED",
    createdAt: hoursAgo(60),
  },
]
